---
title: "Bar Graph"
output: html_notebook
---

```{r}
#install.packages("plotly")

library(tidyverse)
library(data.table)
library(plotly)
```

```{r}
ogDT <- select(read.csv("~/social_indicatorsVis/combined274and275.csv", check.names = FALSE), c(3:13, 15:23))
```

```{r}
sDT <- ogDT %>% 
    filter(Geography == "Canada", 
         Age == "Total - Age", 
         Education == "Total - Highest certificate, diploma or degree",
         `Field of Study` == "Total - Major field of study - Classification of Instructional Programs (CIP) 2016") %>%
  pivot_longer(c(5:11, 13:20), names_to = "Visible Minority Groups", values_to = "Number of People") %>%
  pivot_wider(names_from = Sex, values_from = "Number of People", values_fn = sum)


sDT
```
```{r}
fig <- plot_ly(sDT, x = ~`Visible Minority Groups`, y = ~Female, type = 'bar', name = "Female") %>%
  add_trace(y = ~Male, name = "Male") %>%
  add_trace(y = ~`Total - Sex`, name = "Total - Sex") %>%
  layout(title = "Population of Visible Minority Groups by Education and Field of Study, 2016", 
         yaxis = list(title = 'Number of People'), barmode = 'group')

fig
```
```{r}
ogDT <- select(merge(read.csv("98-400-X2016274_English_CSV_data.csv"), 
                     read.csv("98-400-X2016275_English_CSV_data.csv"), 
                     all = TRUE), 
               c(1, 4, 8, 11, 14, 17:24, 27, 30:38, 41:48))

# Rename the columns
setnames(ogDT, colnames(ogDT), c("Year", "Geography", "Education", "Age", "Sex", "Chinese", "Black", "Filipino", "Latin American", "Arab", "Korean", "Japanese", "Immigrant Status", "Field of Study", "Total Visible Minority", "Total visible minority population", "South Asian", "Southeast Asian", "West Asian", 
"Visible minority, n.i.e.", "Multiple visible minorities", "Not a visible minority", "Generation Status", "Total Visible Minority 2", "Total visible minority population 2", "South Asian 2", "Southeast Asian 2", "West Asian 2", "Visible minority, n.i.e. 2", "Multiple visible minorities 2", "Not a visible minority 2"))
```

```{r}
immDT <- ogDT %>%
  filter(Geography == "Canada", Education == "Total - Highest certificate, diploma or degree", 
         `Field of Study` == "Total - Major field of study - Classification of Instructional Programs (CIP) 2016", 
         Age == "Total - Age", Sex == "Total - Sex") %>%
  select("Chinese", "Black", "Filipino", "Latin American", "Arab", "Korean", "Japanese", "Total Visible Minority", "Total visible minority population", "South Asian", "Southeast Asian", "West Asian", "Visible minority, n.i.e.", "Multiple visible minorities", "Not a visible minority", "Immigrant Status") %>%
  pivot_longer(c(1:15), names_to = "Visible Minority Groups", values_to = "Number of People") %>%
  pivot_wider(names_from = `Immigrant Status`, values_from = "Number of People", values_fn = sum)

immDT
```
```{r}
fig <- plot_ly(immDT, x = ~`Visible Minority Groups`, y = ~Immigrants, type = 'bar', name = "Immigrants") %>%
  add_trace(y = ~`Non-permanent residents`, name = "Non-permanent residents") %>%
  add_trace(y = ~`Non-immigrants`, name = "Non-immigrants") %>%
  add_trace(y = ~`Total - Immigrant status`, name = "Total - Immigrant status") %>%
  layout(title = "Population of Visible Minority Groups by Education, Field of Study and Immigrant Status, 2016", 
         yaxis = list(title = 'Number of People'), barmode = 'group')

fig
```
```{r}
genDT <- ogDT %>%
  filter(Geography == "Canada", Education == "Total - Highest certificate, diploma or degree", 
         Age == "Total - Age", Sex == "Total - Sex")

genDT <- genDT[complete.cases(genDT[ , 23]),]

genDT <- genDT %>%
  select("Chinese", "Black", "Filipino", "Latin American", "Arab", "Korean", "Japanese", "Total Visible Minority 2", "Total visible minority population 2", "South Asian 2", "Southeast Asian 2", "West Asian 2", "Visible minority, n.i.e. 2", "Multiple visible minorities 2", "Not a visible minority 2", "Generation Status") %>%
  pivot_longer(c(1:15), names_to = "Visible Minority Groups", values_to = "Number of People") %>%
  pivot_wider(names_from = `Generation Status`, values_from = "Number of People", values_fn = sum)

genDT
```

```{r}
# Scatter plot
synData <- read.csv("~/social_indicatorsVis/Synthethic data -income and ethnocultural vars.csv", check.names = FALSE)
```

```{r}
synDF <- synData %>%
  filter(`Visible Minority` == "South Asian", Sex == "Female")

synDF
```

```{r}
fit <- lm(`Mean Income` ~ `Percentage employed Full-time`, data = synDF) %>%
          fitted.values()
    
# Plot the scatter plot
sp <- plot_ly(data = synDF, x = ~`Percentage employed Full-time`, y = ~`Mean Income`, 
              type = 'scatter', mode = 'markers',
              text = ~paste('Ethnic origin: ', `Ethnic origins`,
                            '<br> Sex: ', Sex,
                            '<br> Age Group: ', `Age groups`,
                            '<br> Generation: ', `Generation Status`,
                            '<br> Proportion with University degree:', `Proportion with univeristy degree`,
                            '<br> Number of People: ', Counts),
              hovertemplate = paste('<b>Mean Income</b>: $%{y}',
                                    '<br><b>Percentage employed Full-time</b>: %{x}<br>',
                                    '%{text}'),
              color = ~`Visible Minority`,
              width = 1000,
              height = 600) %>%
  add_trace(x = ~`Percentage employed Full-time`, y = fit, mode = "lines") # Regression lines are overlapping

sp <- sp %>%
  layout(title = "Percentage employed Full-time by Mean",
         xaxis = list(title = "Percentage employed Full-time"),
         yaxis = list(title = "Mean income ($)")
         )

sp
```

