---
title: "Choropleth"
output: html_notebook
---

```{r}
#install.packages("leaflet")
#install.packages("tigris")
```

```{r}
library(leaflet)
library(geojsonio)
library(rgdal)
library(tidyverse)
library(data.table)
library(htmltools)
```

```{r}
# Read the GeoJson file
#CMA <- readOGR("~/social_indicatorsVis/TopoJSON/CMA_CA_2016_with_Residuals.json")
CMA <- readOGR("CMA_CA_2016_with_Residuals.json")
```

```{r}
# Read csv file
# Original file: 98-400-X2016214_English_CSV_data.csv
# To make the file, first select columns to keep, then pivot_longer Generation Status
employGen <- read.csv("98-400-X2016_reduced_pivoted_data.csv", check.names = FALSE)

# Data Cleaning
# Change Number of People to Population
setnames(employGen, colnames(employGen[8]), "Population")

# If value in Population column is "F" or "...", assign NA
employGen$Population[employGen$Population == "F" | employGen$Population == "..."] <- NA

# Change Population column to integer
employGen$Population <- as.integer(employGen$Population)

# Change Geography to CMANAME to be the key to merge by
setnames(employGen, colnames(employGen[2]), "CMANAME")

# Remove all rows for Population with 
employGen <- employGen[complete.cases(employGen),]

# Print updated data frame
employGen

# Check the number of and which geographical locations are the same (There are only a total of 30 CITIES that overlap)
print(intersect(CMA@data$CMANAME, unique(employGen$CMANAME)))
```
```{r}
# Lines 55-78 were used to test a method from https://stackoverflow.com/questions/38676580/errors-when-merging-spatialpolygonsdataframe-with-dataset

#library(reshape2)
#library(rmapshaper)

# Make a copy of employGen and subset columns that are constant across all VisMin
#df <- employGen[, c("Year", "CMANAME", "Age", "Sex", "Total income groups", "Generation Status")]
#df <- unique(df)
```

```{r}
# For each column with variables, cast the data into tidy form
#dfVM <- dcast(employGen, CMANAME ~ `Visible minority`, value.var = "Population")
#dfVM
```

```{r}
#CMA@data <- merge(CMA@data, dfVM)
#CMA@data <- merge(CMA@data, df)
#CMA@data

#plot(CMA, asp = 1, col = CMA@data$Arab)
#plot(CMA, asp = 1, col = CMA@data$Chinese)
```

```{r}
# The user should filter by everything except Geography, and the Choropleth displays population
filtered_EG <- employGen %>%
  filter(`Visible minority` == "Total - Visible minority", Age == "Total - Age", 
         Sex == "Total - Sex", `Total income groups` == "Total - Total income", 
         `Generation Status` == "Total - Generation status")

# Print the filtered data frame
filtered_EG
```

```{r}
# When merging the data, there should only be 30 rows (The intersect of CMANAME)
# Merge the data and select the columns to keep
CMA@data <- select(merge(CMA@data, filtered_EG, by = "CMANAME"), c("CMANAME", "Visible minority", "Age", "Sex", 
                                                   "Total income groups", "Generation Status",
                                                   "Population"))

# Display to confirm
CMA@data
```

```{r}
# Create the ranges for the bins (8 ranges to fit colour palette)
bins <- c(0, 100000, 200000, 300000, 400000, 500000, 600000, 700000, Inf)

# Colour palette for the intervals
pal <- colorBin("Purples", domain = CMA$Population, bins = bins)

hoverText <- sprintf(
  "<strong>Visible Minority: %s</strong>
  <br>Geography: <em>%s</em>
  <br>Number of People: <em>%d</em>
  <br>Age: %s
  <br>Sex: %s 
  <br>Total income groups: %s 
  <br>Generation Status: %s", 
  CMA@data$`Visible minority`, CMA@data$CMANAME,CMA@data$Population, CMA@data$Age,
  CMA@data$Sex, CMA@data$`Total income groups`, CMA@data$`Generation Status`
) %>% lapply(htmltools::HTML)

# Create the choropleth
leaflet(CMA) %>%
  setView(-106.3, 56.1, zoom = 3.5) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(Population),
    weight = 2,
    opacity = 1,
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = hoverText,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(pal = pal, values = ~Population, opacity = 0.7, title = "Number of People", position = "topright")
```
