---
title: "Choropleth"
output: html_notebook
---

```{r}
#install.packages("leaflet")
```

```{r}
library(tidyverse)
library(data.table)
library(readxl)
library(leaflet)
library(rgdal)
library(htmltools)
```

```{r}
# Read the GeoJson file
CAN <- readOGR("gfedTopo.json")

# Keep only FEDENAME as keys to merge by
CAN@data <- select(CAN@data, "FEDENAME")

# Rename it to match with VoterTurnout
names(CAN@data) <- "Electoral District Name"

CAN@data
```

```{r}
# Read xlsx file
# Read the sheets separately and remove unnecessary columns
voterTurnout <- select(as.data.frame(read_excel("FED- vismin, income and voting data.xlsx", sheet = 1)),
                       -"Electoral District Number")
income <- select(as.data.frame(read_excel("FED- vismin, income and voting data.xlsx", sheet = 2)),
                 -"Geo_Code")
vismin <- select(as.data.frame(read_excel("FED- vismin, income and voting data.xlsx", sheet = 4)),
                 -"Geo_Code")

# Change names to match with voterTurnout
names(income) <- c("Province", "Electoral District Name", "Average after-tax household income ($)")
names(vismin) <- c("Province", "Electoral District Name", "Visible Minority Groups",
                   "Total", "Male", "Female", "Percentage Female", "Percentage Male")

# Print
voterTurnout
income
vismin
```

```{r}
# Calculate average for income
income <- income %>%
  group_by(Province, `Electoral District Name`) %>%
  summarise(`Average after-tax household income ($)` = mean(`Average after-tax household income ($)`),
            .groups = 'drop')

# Print
income
```

```{r}
# The user can only filter by VisMin
filtered_VM <- filter(vismin, `Visible Minority Groups` == "West Asian")

# Print the filtered data frame
filtered_VM
```

```{r}
# Merge the data
CAN@data <- left_join(CAN@data, voterTurnout)
CAN@data <- left_join(CAN@data, income)
CAN@data <- left_join(CAN@data, filtered_VM)

# Display to confirm
CAN@data
```

```{r}
# User can choose what to fill the choropleth by
# The choices are: Population, Electors, Polling Stations, Valid Ballots, Rejected Ballots, Total Ballots
# Cast, Average after-tax household income ($), Total, Male, Female

choice="Population"
```

```{r}
# Create the ranges for the bins (8 ranges to fit colour palette)
# Find the max value in the selected column and divide by 8 
interval <- max(CAN@data[[choice]])/8

# Count the number of significant digits
# Subtract one and make it negative (since R counts 1's digit at 0)
sd <- (ceiling(log10(interval))-1)*-1

# Create the bins
bins <- c(round(interval, sd) * 0:7, Inf)

# Colour palette for the intervals
pal <- colorBin("Blues", domain = CAN@data[[choice]], bins = bins)

hoverText <- sprintf(
  "<strong>Visible Minority: %s</strong>
  <br>Province: <em>%s</em>
  <br>Electoral District Name: <em>%s</em>
  <br>Population: %d
  <br>Electors: %d
  <br>Polling Stations: %d
  <br>Valid Ballots: %d
  <br>Valid Ballots %%: %f
  <br>Rejected Ballots: %d
  <br>Rejected Ballots %%: %f
  <br>Total Ballots Cast: %d
  <br>Voter Turnout %%: %f
  <br>Average after-tax household income ($): %f
  <br>Total: %d
  <br>Male: %d
  <br>Female: %d
  <br>Percentage Male: %f
  <br>Percentage Female: %f", 
  CAN@data$`Visible Minority Groups`, CAN@data$Province, CAN@data$`Electoral District Name`,
  CAN@data$Population, CAN@data$Electors, CAN@data$`Polling Stations`, CAN@data$`Valid Ballots`,
  CAN@data$`Valid Ballots %`, CAN@data$`Rejected Ballots`, CAN@data$`Rejected Ballots %`,
  CAN@data$`Total Ballots Cast`, CAN@data$`Voter Turnout %`, 
  CAN@data$`Average after-tax household income ($)`, CAN@data$Total, CAN@data$Male,
  CAN@data$Female, CAN@data$`Percentage Male`, CAN@data$`Percentage Female`
) %>% lapply(htmltools::HTML)

# Create the choropleth
leaflet(CAN) %>%
  setView(-106.3, 56.1, zoom = 2.5) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(CAN@data[[choice]]),
    weight = 2,
    opacity = 1,
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = hoverText,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "12px",
      direction = "auto"
    )
  ) %>%
  addLegend(pal = pal, values = ~CAN@data[[choice]], opacity = 0.7, title = choice, position = "topright")
```
